ARG PLATFORM=linux/amd64

# Build stage
FROM --platform=${PLATFORM} gradle:8.10.2-jdk17 AS builder
WORKDIR /app
COPY . .
ARG SPRING_PROFILES_ACTIVE
ARG SERVICE
RUN gradle build --no-daemon -Penv=${SPRING_PROFILES_ACTIVE} -Pservice=${SERVICE}

# Production stage
FROM --platform=${PLATFORM} eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar ./
ARG SPRING_PROFILES_ACTIVE
ARG SERVICE
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV APP_SERVICE=${SERVICE}
EXPOSE 8080

# Create a script to find and run the JAR file
RUN echo '#!/bin/sh\n\
JAR_FILE=$(ls -1 *.jar | head -n 1)\n\
if [ -z "$JAR_FILE" ]; then\n\
    echo "No JAR file found in the current directory"\n\
    exit 1\n\
fi\n\
exec java -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -Dapp.service=$APP_SERVICE -jar $JAR_FILE' > /app/run.sh && chmod +x /app/run.sh

ENTRYPOINT ["/app/run.sh"]