# Dockerfile-nextjs
ARG PLATFORM=linux/amd64

# Build stage
FROM --platform=${PLATFORM} node:22.10.0-alpine AS builder
WORKDIR /app

ARG NODE_ENV=dev
ENV NODE_ENV=${NODE_ENV}

COPY package*.json ./
RUN npm ci --include=dev
COPY . .
RUN npm run build

# Production stage
FROM --platform=${PLATFORM} node:22.10.0-alpine AS runner
WORKDIR /app

ARG NODE_ENV=dev
ENV NODE_ENV=${NODE_ENV}
ENV PATH /app/node_modules/.bin:$PATH

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# 캐시 정리
RUN npm cache clean --force && \
    rm -rf /root/.npm

EXPOSE 3000
CMD ["node", "server.js"]