# secret-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secrets
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${APP_NAME}
    app.kubernetes.io/instance: ${APP_NAME}-${ENV}
    app.kubernetes.io/part-of: ${PROJECT_NAME}
    env: ${ENV}
type: Opaque
stringData:
  DB_HOST: "${DB_HOST}"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  DB_PORT: "${DB_PORT}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  LOG_LEVEL: "${LOG_LEVEL}"
  NODE_ENV: "${ENV}"
  APP_URL: "${APP_URL}"